#!/bin/sh

[ -d "$HOME/.config" ] ||  mkdir -p $HOME/.config;

cp -r .config/* $HOME/.config
cp .vimrc .gtkrc-2.0 .xinitrc $HOME
echo "copied config files"
cp -r dmenu-scripts $HOME
echo "copied custom scripts"

