#!/bin/sh

rm .xinitrc .vimrc .gtkrc-2.0 .zshrc .bashrc
rm -rf .config Scripts
mkdir .config

cp $HOME/.vimrc $PWD
cp $HOME/.zshrc $PWD
cp $HOME/.bashrc $PWD
cp $HOME/.xinitrc $PWD
cp $HOME/.gtkrc-2.0 $PWD
cp $HOME/.cfgignore $PWD
cp -r $HOME/.config/bspwm $PWD/.config/
cp -r $HOME/.config/sxhkd $PWD/.config/
cp -r $HOME/.config/fish $PWD/.config/
cp -r $HOME/.config/polybar $PWD/.config/
cp -r $HOME/.config/picom $PWD/.config/
cp -r $HOME/.config/vifm $PWD/.config/
cp -r $HOME/.config/gtk-3.0 $PWD/.config/
cp -r $HOME/.config/fontconfig $PWD/.config/
cp -r $HOME/.config/nvim $PWD/.config/
cp -r $HOME/Scripts $PWD/Scripts
cp $HOME/Programs/dmenu/dmenu_history $PWD/dmenu
cp $HOME/Programs/dmenu/config.h $PWD/dmenu
cp $HOME/Programs/st/config.h $PWD/st

git add .
git commit -m "$1"
git push origin master
