#!/bin/bash
GIF=$(printf '%s.gif' $(cut -d '.' -f 1 <(echo $1)))
echo $GIF
ffmpeg -y -i $1 -vf palettegen /tmp/palette.png
ffmpeg -y -i $1 -i /tmp/palette.png -filter_complex paletteuse -r 10 $GIF
rm /tmp/palette.png
