#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0	

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config top_pading		 10
bspc config single_monocle true

#bspc config focused_border_color "#596ed8"
bspc config focused_border_color "#7cb7ff"
bspc config presel_feedback_color "#a296ff"
bspc rule -a feh state=floating
bspc rule -a Nmtui-st state=floating
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Gpick state=floating

