#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0	

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_pading		 10

bspc config focused_border_color "#596ed8"
bspc config presel_feedback_color "#a296ff"
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Firefox desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Deezer state=pseudo_tiled 
bspc rule -a feh state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Gpick state=floating

