#!/bin/sh
#cat /home/ap/.cache/drun_cache | xargs which | grep -o '[^/]*$' | tee /home/ap/.cache/drun_cache
cached=$(cat /home/ap/.cache/drun_cache)
dmenu_path | grep -Fx "$cached" | tee /home/ap/.cache/drun_cache
