colors:
  bright:
    black: '#555b68'
    blue: '#81a1c1'
    cyan: '#88c0d0'
    green: '#a3be8c'
    magenta: '#b48ead'
    red: '#e9837b'
    white: '#e5e9f0'
    yellow: '#ebcb8b'
  cursor:
    cursor: '#fece35'
    text: '#555555'
  normal:
    black: '#282c35'
    blue: '#81a1c1'
    cyan: '#88c0d0'
    green: '#a3be8c'
    magenta: '#b48ead'
    red: '#e9837b'
    white: '#e5e9f0'
    yellow: '#ebcb8b'
  primary:
    background: '#1c1f27'
    foreground: '#d8dee9'
env:
  TERM: xterm-256color
font:
  normal:
    family: Noto Sans Mono
  offset:
    x: 0
    y: 0
  size: 9.5
shell:
  program: /bin/zsh
cursor:
    style: Beam
