#!/bin/sh

player_status=$(playerctl --player=deezer status 2> /dev/null)

if [ "$player_status" = "Playing" ] || [ "$player_status" = "Paused" ]; then
   echo "$(playerctl --player=deezer metadata --format '{{artist}} - {{title}}')"
else
   echo ""
fi
